version: '3'
services:
  database: 
    image: mysql
    ports:
      - "1000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password@123"
      MYSQL_DATABASE: "test"
  backend:
    image: backend
    # build: .
    ports: 
      - "80:80"
    links:
      - database
    # command: bash
    # stdin_open: true
    # tty: true 
    command: go run database.go


